config/routes.rb
Rails.application.routes.draw do
  resources :products, :categories
  
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  
  attachment :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(allowed_params)
    if @category.save
      flash[:notice] = "Successfully created category."
      redirect_to @category
    else
      render :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(allowed_params)
      flash[:notice] = "Successfully updated category."
      redirect_to @category
    else
      render :edit
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Successfully destroyed category."
    redirect_to categories_url
  end
  
  private
  
  def allowed_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order('created_at DESC').limit(10)
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(allowed_params)
    if @product.save
      flash[:notice] = "Successfully created product."
      redirect_to @product
    else
      render :new
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(allowed_params)
      flash[:notice] = "Successfully updated product."
      redirect_to @product
    else
      render :edit
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Successfully destroyed product."
    redirect_to products_url
  end
  
  private
  
  def allowed_params
    params.require(:product).permit(:name, :price, :category_id, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Refil</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
      <%- end -%>
            
      <%= yield %>
    </div>
  </body>

</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <p>
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
  	<%= f.attachment_field :photo %>
  </p>
  
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/products/edit.html.erb
<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

app/views/products/index.html.erb
<% for product in @products %>
  <div class="product">
    <h3>
      <%= link_to h(product.name), product %>
      <%= number_to_currency(product.price) %>
    </h3>
    Category: <%=h product.category.name %>

  </div>
<% end %>

app/views/products/new.html.erb
<%= render :partial => 'form' %>

<p><%= link_to "Back to List", products_path %></p>

app/views/products/show.html.erb
<%= simple_format h(@product.description) %>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @product.price %>
</p>

<%= image_tag attachment_url(@product, :photo, :fill, 300, 300, format: "gif") %>

<% unless @product.category.nil? %>
<p>
  <strong>Category:</strong>
  <%= link_to h(@product.category.name), @product.category %>
</p>
<% end %>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>